### ISSUE TITLE
Please add algo

### ISSUE THREAD

**Issue by ngasep** [MaynardMiner/MM.Hash#12]
Please add algo equihash 192.7 (zero)
Mine use optiminer zero, lolminer zero,ewbf new 0.3

**Comment by MaynardMiner** [comment]
I see. Zerg added Equihash192.

I'll work on it now.

**Comment by MaynardMiner** [comment]
I added for windows version- Clone directly from git to use. I can't make release until I do Linux side, and I have no access to linux computer from where I am at.

**Comment by MaynardMiner** [comment]
Update: I am working on a re-write for the Unix side, trying to make it operate without needing a display manager, so it can work straight from tty.

I will add for Unix when I finish that project.

**Comment by MaynardMiner** [comment]
EWBF has been added to Unix version. Closing issue. Release hasn't been made yet, but you can clone.
