### ISSUE TITLE
Parameters in 1.3.9

### ISSUE THREAD

**Issue by Hermarcel** [MaynardMiner/MM.Hash#16]
Just started my first test with MM.Hash (v1.3.9). I get the following error:
"A parameter cannot be found that matches parameter name 'GPU_Count1"
When I remove this parameter from the custom miner configuration, a few parameters seems to be processed ok, but then:
"A parameter cannot be found that matches parameter name Algorithm"

I am still a complete noob regarding mining, HiveOS, everything. ;)

**Comment by MaynardMiner** [comment]
You no long need -GPU_Count1

Miner now detects gpus

**Comment by Hermarcel** [comment]
ok, but after emoving it, the same happens to paramater "Algorithm". Delete that one as well?

**Comment by MaynardMiner** [comment]
Yes

It's depreciated too. Config >> nvidia-algorithms.txt is now what you modify.

Or you can do it remotely, by using -No_Algo argument.

**Comment by MaynardMiner** [comment]
This all just happened this version. It's probably where the confusion is coming from.

Where did you get these arguments from, so I can fix the wiki?

**Comment by Hermarcel** [comment]
From https://github.com/MaynardMiner/MM.Hash/blob/master/MM.Hash.conf.sample

Thanks for the fast replies :)

**Comment by MaynardMiner** [comment]
Crap. I'll fix it. Sorry about that confusion.

**Comment by Hermarcel** [comment]
O, there's a wiki... Missed it, sorry

**Comment by MaynardMiner** [comment]
I fixed it so that next release will have correct .conf example. I missed it in last release.

If you have further questions for use, I suggest joining discord and asking there. Users have been helping each other out.

This is obviously new to everyone, being the first hiveos software, so we are all helping each other out.

I fixed .conf. I will close.

**Comment by MaynardMiner** [comment]
I just noticed that the discord link wasn't working on readme.md after I wrote that.

I updated it, in case you tried to join earlier.
