### ISSUE TITLE
HMQ1725

### ISSUE THREAD

**Issue by MaynardMiner** [MaynardMiner/MM.Hash#2]
I have been noticing that HMQ1725 algo using Tpruvot CCminer has not been stable for on my miner- It continues to shutdown. Please let me know if anyone else can reproduce.

I am looking for another compilable ccminer that supports HMQ1725.

**Comment by slovke** [comment]
ccminer trupvot 225 hmq1725 i use on 1080ti when it switches to it but moslty Cpu runs that algo on cpuminer-opt-3.8.8

**Comment by MaynardMiner** [comment]
I'm seeing it happen with other miners now, too actually (I missed it) I placed a hold on xterm...And found that it was a memory allocation corruption.

I'm pretty sure it has something to do with the fact that I'm trying to run it all on a USB 2.0 stick. It may not be fast enough to run both miners and MM.Hash together. I'm going to build a hdd, and load it on and see if it continues.

I think it may need to be usb 3.0 at the very least, since gui is needed on Ubuntu.

**Comment by slovke** [comment]
Just buy damm ssd 😁

**Comment by MaynardMiner** [comment]
I agree with you- I'm more testing to see if USB will work. It's very useful for people with multiple mining rigs who need to fast-swap OS's, and also useful for smaller devices (Microcontrollers, Tablets, Phones, PS4). But overall the best way to run a larger rig is with SSD.

The big reason one would want a linux miner is for larger rigs (8+, because Linux is bulletproof if setup right), and for support with ARM architecture.

So far the testing with USB 2.0, works- It's just sluggish to load new miner windows, and sometimes memory corruption error pops. I ordered a 3.0 stick and will test with it soon and see if I can reproduce issue. I think its simply because it's USB 2.0, not 3.0

**Comment by MaynardMiner** [comment]
I've realized this was a linux build issue. The original setup downloaded Cuda 8, but I was using cuda 390 drivers.

It also helped greatly by dividing device type (I was running two different cards in one machine for testing.)

I updated readme with new linux Nvidia procedure. Did updates to avoid bugs.

Closing issue.
